Update Albania generation capacity
electricitymap/electricitymap-contrib pull request #4321
Opened 2022-07-03 16:27 UTC by autipial

This PR updates Albania generation capacity based on ERE (energy regulator of Albania) data.
Related to #4180.

2022-07-03 19:28 UTC, VIKTORVAV99 requested changes
Biomass capacity should be kept and IRENA should still be the source for it.

2022-07-03 19:28 UTC, VIKTORVAV99 commented on DATA_SOURCES.md
> +- Albania: [ERE](https://ere.gov.al/images/2022/04/Raporti%20Vjetor%202021%20perfundimtare.pdf)
```suggestion
- Albania:
  - Biomass: [IRENA](https://www.irena.org/publications/2022/Apr/Renewable-Capacity-Statistics-2022)
  - Other: [ERE](https://ere.gov.al/images/2022/04/Raporti%20Vjetor%202021%20perfundimtare.pdf)
```

2022-07-03 19:28 UTC, VIKTORVAV99 commented on config/zones.json
> +      "solar": 23
```suggestion
      "biomass": 1,
      "gas": 98,
      "hydro": 2484,
      "solar": 23
```

2022-07-03 20:32 UTC, autipial commented
I am very surprised by the reference from IRENA to this 1MW of biomass/bioenergy capacity, since I never saw it mentioned in any document related to the electricity grid of Albania (especially in the documents published by Albania's electricity producers / transmitter / distributor / regulator).
Even IRENA itself doesn't mention it in its [assessment of Albania's renewable capacities](https://www.irena.org/publications/2021/March/Renewables-Readiness-Assessment-Albania) in 2021.

Of course if you think it is best to keep it, I will amend the PR.

BTW I realize that I also made a mistake regarding the thermal power plant of Vlorë -- it is designed to be able to burn gas, but its primary combustible is oil. I will change the PR accordingly.

2022-07-03 20:43 UTC, VIKTORVAV99 commented
> https://www.irena.org/publications/2022/Apr/Renewable-Capacity-Statistics-2022

Technically it's not biomass per say but renewable municipal waste but currently electricityMap treats waste as biomass so that is where the 1 MW comes from.

2022-08-13 07:24 UTC, VIKTORVAV99 approved these changes

2022-08-13 19:05 UTC, merged