Add timestamps to tooltips
electricitymap/electricitymap-contrib pull request #4506
Opened 2022-08-27 15:27 UTC by Raader

## Issue
#4488 
## Description
Adding timestamps to all tooltips
### Preview
<img width="754" alt="Screen Shot 2022-08-27 at 18 25 53" src="https://user-images.githubusercontent.com/48628713/187036767-0f5039f8-cb38-4eeb-9247-55d8b5c1fe79.png">
<img width="754" alt="Screen Shot 2022-08-27 at 18 25 57" src="https://user-images.githubusercontent.com/48628713/187036769-821061ce-bf37-4a02-bbcd-13e8ef52f4df.png">
<img width="754" alt="Screen Shot 2022-08-27 at 18 26 05" src="https://user-images.githubusercontent.com/48628713/187036771-641dcd76-c183-46ab-84f8-3edb6de0bbd8.png">
<img width="754" alt="Screen Shot 2022-08-27 at 18 26 09" src="https://user-images.githubusercontent.com/48628713/187036772-d3e813f7-ced2-454c-bfa3-878c5b7ded7f.png">

2022-08-27 17:37 UTC, VIKTORVAV99 requested changes
Overall this looks good but I added a few suggestions that should be addressed. Since we know the zone data will always exist then these views are shown and that it should always have a datetime we can remove the redundant checks for it.

I also think it would be great if you could update the carbon intensity graph in this PR as well so it also has the date time on top like the other graphs.

Currently it is below the main title as seen here:
![image](https://user-images.githubusercontent.com/30777521/187041554-bac61a45-3afc-4e86-8b83-e47ab6ce649b.png)

2022-08-27 17:37 UTC, VIKTORVAV99 commented on web/src/components/tooltips/countrypanelexchangetooltip.jsx
> +      <StyledTimeDisplay date={zoneData.stateDatetime ? new Date(zoneData.stateDatetime) : null} />
```suggestion
      <StyledTimeDisplay date={zoneData.stateDatetime} />
```

2022-08-27 17:37 UTC, VIKTORVAV99 commented on web/src/components/tooltips/countrypanelproductiontooltip.jsx
> +      <StyledTimeDisplay date={zoneData.stateDatetime ? new Date(zoneData.stateDatetime) : null} />
```suggestion
      <StyledTimeDisplay date={zoneData.stateDatetime} />
```

2022-08-27 17:37 UTC, VIKTORVAV99 commented on web/src/components/tooltips/pricetooltip.jsx
> +      <StyledTimeDisplay date={zoneData.stateDatetime ? new Date(zoneData.stateDatetime) : null} />
```suggestion
      <StyledTimeDisplay date={zoneData.stateDatetime} />
```

2022-08-27 18:08 UTC, Raader commented
@VIKTORVAV99 updated carbon intensity graph.

2022-08-27 18:33 UTC, VIKTORVAV99 requested changes
Just one more suggestion then I looks ready to me.

2022-08-27 18:33 UTC, VIKTORVAV99 commented on web/src/components/tooltips/mapcountrytooltip.jsx
> +      <StyledTimeDisplay date={zoneData.stateDatetime ? new Date(zoneData.stateDatetime) : null} />
```suggestion
      <StyledTimeDisplay date={zoneData.stateDatetime} />
```

2022-08-27 18:49 UTC, VIKTORVAV99 approved these changes
LGTM!

@rasmusjeppsen what do you think, any design feedback that needs to be addressed?

@Kongkille am I right in assuming every datapoint will always have a datetime object and the checks aren't needed?

2022-08-29 09:51 UTC, rasmusjeppsen commented
> @rasmusjeppsen what do you think, any design feedback that needs to be addressed?

Thank you for providing a PR for this, @Raader! Looks great. And thank you for your input/review @VIKTORVAV99. Much appreciated!

In terms of the design, I think increasing the visibility of the timestamp by making the text bold would be a nice detail to add.
Here are some design mockups based on the screenshots @Raader provided in the PR to illustrate:

![timestamp_mockup](https://user-images.githubusercontent.com/58597172/187169859-2d6fdd8d-068c-4e76-9f6a-ecd5aa591ca6.png)
![timestamp_mockup2](https://user-images.githubusercontent.com/58597172/187170367-6f86e0be-66c9-44d5-9d53-8a0717039809.png)

> I also think it would be great if you could update the carbon intensity graph in this PR as well so it also has the date time on top like the other graphs.

Nice catch, Viktor! I agree - this would be great for consistency.

One thing to note here is that we show the country first and then the timestamp second when hovering on the map zones (outside the sidepanel graphs), which then arguably leads to some inconsistency of the sidepanel vs. the map.

<img width="497" alt="zone_hover_example" src="https://user-images.githubusercontent.com/58597172/187172188-84efb037-cc65-4620-8b6f-c96112c81e4c.png">

I do, however, think that in terms of the hierarchy of information displayed, the country is the essential information when navigating/browsing the map, whereas the timestamp is the essential information for the graphs on the sidepanel.
So, **TLDR;** I agree with updating the carbon intensity graph, but think we should keep the layout of having the country first and timestamp second when hovering over the zones on the map. We could address this in a future PR to improve overall consistency if need be.

Great work!

2022-08-29 13:38 UTC, Raader commented
@rasmusjeppsen even though I think making timestamps bold will make it look better, wouldn't it introduce even greater inconsistency between the map tooltips and the sidebar tooltips. Updating the map tooltips appearance is might be out of scope for this PR.

2022-08-29 16:00 UTC, rasmusjeppsen commented
> @rasmusjeppsen even though I think making timestamps bold will make it look better, wouldn't it introduce even greater inconsistency between the map tooltips and the sidebar tooltips. Updating the map tooltips appearance might be out of scope for this PR.

@Raader I understand the concern regarding inconsistency, however, I think making the timestamps bold in the tooltips for the sidepanel is the right step forward here whilst keeping the following position of the timestamp for the sidepanel as per your preview:
![image](https://user-images.githubusercontent.com/58597172/187242349-ead5077c-3d72-40fa-9ec0-05ae34196250.png)

And this position for the map as it currently is:
![image](https://user-images.githubusercontent.com/58597172/187242426-82d72d94-b689-4550-a8c6-145d904dae3a.png)

I also think that making the timestamps bold in the side panel will further differentiate the layout of tooltips in the sidepanel vs. when hovering on zones on the map which IMO makes the two layouts prioritize the display of information differently (timestamp vs. country first), rather than making it inconsistent in a bad/unthoughtful way.

I suggest we add the bold text to the timestamps in the sidepanel and then everything LGTM!

2022-08-29 16:11 UTC, Raader commented
@rasmusjeppsen 
> I also think that making the timestamps bold in the side panel will further differentiate the layout of tooltips in the sidepanel vs. when hovering on zones on the map which IMO makes the two layouts prioritize the display of information differently (timestamp vs. country first), rather than making it inconsistent in a bad/unthoughtful way.
> 
Makes sense. Made them bold.

2022-08-30 10:41 UTC, VIKTORVAV99 commented
> > @Kongkille am I right in assuming every datapoint will always have a datetime object and the checks aren't needed?
> 
> @VIKTORVAV99 @Kongkille Map country tooltip(the one which had timestamps already) originally had a date time check. Maybe we should've kept those checks just in case.

I think it should be safe as the backend fill the dates for empty values and the graphs should not be visible at all without this data but we'll see what Kongkille says. And even if there is checks needed we could simplify them with optional chaining anyway.

2022-08-30 15:10 UTC, Kongkille commented
> @Kongkille am I right in assuming every datapoint will always have a datetime object and the checks aren't needed?

Yes that should always be the case

2022-08-30 15:20 UTC, Kongkille reviewed
Looks great!

On the code side of things, I'm seeing a bit of duplication in the styling, it's not a big deal but the timedisplay could have a default styling corresponding to the shared styling and then we can override for edge cases.

You could do that by styling the <p> tag in timeDisplay.jsx

On UI, I think it looks great and is intuitive. Have you considered adding some kind of clock icon next to the date? 

![image](https://user-images.githubusercontent.com/45588799/187475933-87cb80ca-cda8-4a1e-a4ee-80717c7c46e7.png)

2022-08-30 15:38 UTC, VIKTORVAV99 commented
> Looks great!
> 
> On the code side of things, I'm seeing a bit of duplication in the styling, it's not a big deal but the timedisplay could have a default styling corresponding to the shared styling and then we can override for edge cases.
> 
> You could do that by styling the
> 
> tag in timeDisplay.jsx
> 
> On UI, I think it looks great and is intuitive. Have you considered adding some kind of clock icon next to the date?
> 
> ![image](https://user-images.githubusercontent.com/45588799/187475933-87cb80ca-cda8-4a1e-a4ee-80717c7c46e7.png)

Adding a icon is a good idea, but I think maybe a calendar icon would be a better fit?
Or switching between a clock icon for "live" view and a calendar icon for historical view.
Calendar month icon:
![calendar_month_FILL0_wght400_GRAD0_opsz48](https://user-images.githubusercontent.com/30777521/187479722-00dab67b-09d3-4272-91d3-a0f90abd8c80.svg)

Or perhaps the date range or today icon:
![date_range_FILL0_wght400_GRAD0_opsz48](https://user-images.githubusercontent.com/30777521/187479172-66e0bd6a-9bc2-492b-bd74-19c2657fd3ac.svg)
![today_FILL0_wght400_GRAD0_opsz48](https://user-images.githubusercontent.com/30777521/187479202-bc00b20b-043d-4ccb-a6dc-b53a857d2f75.svg)

Or a combination of date range/calendar month, today, and the clock depending on the selected time resolution? (If this is believed to be outside the scope of the PR I can create a subsequent PR with the icon changes.)

2022-08-30 18:19 UTC, Raader commented
> Or a combination of date range/calendar month, today, and the clock depending on the selected time resolution? (If this is believed to be outside the scope of the PR I can create a subsequent PR with the icon changes.)

@VIKTORVAV99 I think you should open a subsequent PR.

2022-08-31 10:03 UTC, Kongkille approved these changes
I think this is good to go!

Thanks a lot @Raader for driving this through

2022-09-07 17:41 UTC, Raader commented
@Kongkille is there something that keeps this from being merged?

2022-09-07 18:02 UTC, VIKTORVAV99 commented
> @Kongkille is there something that keeps this from being merged?

Kongkille is on vacation but I don't think there is anything blocking it.
@tonypls what do you think, we should be able to merge this right?

2022-09-08 06:37 UTC, tonypls commented
> > @Kongkille is there something that keeps this from being merged?
> 
> Kongkille is on vacation but I don't think there is anything blocking it. @tonypls what do you think, we should be able to merge this right?

Yes this is good to go! 🚀 

@Raader Feel free to hit the merge button when the tests have passed 👌

2022-09-08 13:21 UTC, tonypls commented
Ah okay that makes sense 😄  I'll merge it for ya. Nice work!

2022-09-08 13:25 UTC, merged